### ISSUE TITLE
No such file or directory: 'keep_keys.cfg'

### ISSUE THREAD

**Issue by ZhuYun97** [MLNLP-World/SimBiber#12]
The program encounters bugs when attempting to simplify bibliographies. I have also tried it on a Linux server and encountered the same error.
```
> simbiber -i refs.bib -o out.bib

100%|█████████████████████████████████████████████████████████████████████████████| 248/248 [00:00<00:00, 62167.55it/s]
Traceback (most recent call last):
  File "\\?\G:\anaconda\Scripts\simbiber-script.py", line 33, in <module>
    sys.exit(load_entry_point('simbiber', 'console_scripts', 'simbiber')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\xxx\desktop\paper\graphllm\simbiber\Simbiber\main.py", line 36, in main
    sim_biber.simplify()
  File "c:\users\xxx\desktop\paper\graphllm\simbiber\Simbiber\SimBiberTool.py", line 78, in simplify
    self.__simplify__()
  File "c:\users\xxx\desktop\paper\graphllm\simbiber\Simbiber\SimBiberTool.py", line 53, in __simplify__
    self.__simplify_and_write__(s)
  File "c:\users\xxx\desktop\paper\graphllm\simbiber\Simbiber\SimBiberTool.py", line 18, in __simplify_and_write__
    self.bib.simplify_bib(s)
  File "c:\users\xxx\desktop\paper\graphllm\simbiber\Simbiber\BibTool.py", line 118, in simplify_bib
    self.bib_database.entries[self.index]=self.__simplify_bib__(item)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\xxx\desktop\paper\graphllm\simbiber\Simbiber\BibTool.py", line 49, in __simplify_bib__
    with open("keep_keys.cfg") as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'keep_keys.cfg'
```

**Comment by ZhuYun97** [comment]
refer to [https://github.com/MLNLP-World/SimBiber/issues/6](https://github.com/MLNLP-World/SimBiber/issues/6)
